[project]
name = "pacdb"
version = "0.2.0"
description = "Pure-python module to parse and read pacman sync dbs."
authors = [{ name = "Jeremy Drake", email = "github@jdrake.com" }]
requires-python = ">=3.9.0,<4"
readme = "README.md"
license = "MIT"
dependencies = ["zstandard"]

[project.urls]
Repository = "https://github.com/msys2/pacdb"

[dependency-groups]
dev = []

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
